### ISSUE TITLE
Limit max token size

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/blf_01#8]
```
ERROR [2023-10-16 18:19:46,962] ({Executor task launch worker for task 27030} Logging.scala[logError]:94) - Exception in task 197.0 in stage 319.0 (TID 27030)
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at sun.nio.cs.UTF_8.newDecoder(UTF_8.java:68)
        at java.lang.StringCoding.decode(StringCoding.java:213)
        at java.lang.String.<init>(String.java:463)
        at java.lang.String.<init>(String.java:515)
        at com.teragrep.blf_01.Token.toString(Token.java:85)
        at com.teragrep.functions.dpf_03.TokenAggregator.$anonfun$finish$1(TokenAggregator.scala:82)
        at com.teragrep.functions.dpf_03.TokenAggregator$$Lambda$36/263211599.apply(Unknown Source)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:134)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at com.teragrep.functions.dpf_03.TokenAggregator.finish(TokenAggregator.scala:82)
        at com.teragrep.functions.dpf_03.TokenAggregator.finish(TokenAggregator.scala:59)
        at org.apache.spark.sql.execution.aggregate.ComplexTypedAggregateExpression.eval(TypedAggregateExpression.scala:261)
        at org.apache.spark.sql.catalyst.expressions.aggregate.TypedImperativeAggregate.eval(interfaces.scala:545)
        at org.apache.spark.sql.execution.aggregate.AggregationIterator$$anonfun$generateResultProjection$1.apply(AggregationIterator.scala:231)
        at org.apache.spark.sql.execution.aggregate.AggregationIterator$$anonfun$generateResultProjection$1.apply(AggregationIterator.scala:223)
        at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.next(ObjectAggregationIterator.scala:86)
        at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.next(ObjectAggregationIterator.scala:33)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:624)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
```

**Comment by kortemik** [comment]
stacktrace shows dpf_03 as culprit, I assume that dpf_03 is keeping too much data in memory resolve in https://github.com/teragrep/dpf_03/issues/15
